name:                scheme-hs
version:             0.1
synopsis:            Simple Scheme
license-file:        LICENSE
author:              "Guim Caballero"

default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- base  >= 4.8 && <5.0
- array
- bytestring
- containers
- directory
- haskeline
- mtl
- optparse-applicative
- parsec
- text
- transformers
- HTTP
- tasty
- tasty-golden
- hspec

ghc-options:
- -Werror
- -fno-warn-unused-do-bind
- -fno-warn-unused-binds
- -fno-warn-type-defaults
- -fno-warn-type-defaults
- -fno-warn-name-shadowing
- -fwarn-duplicate-exports
- -fwarn-dodgy-exports
- -fwarn-dodgy-imports
- -fwarn-incomplete-patterns
- -fwarn-incomplete-record-updates
- -fwarn-missing-fields
- -fwarn-missing-methods
- -fwarn-orphans
- -fwarn-overlapping-patterns
- -fwarn-unused-imports
- -fwarn-tabs
- -fwarn-unrecognised-pragmas

library:
  source-dirs: src/

executables:
  scheme:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base >= 4.8 && < 5
    - scheme-hs

tests:
  test:
    main: Main.hs
    source-dirs: test-hs/Spec/
    dependencies:
    - scheme-hs
    - hspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
